# Generated by Django 4.0.6 on 2022-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_app', '0002_alter_actividades_options_alter_alumnos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profesores'),
        ),
    ]
