# Generated by Django 4.0.6 on 2022-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club_app', '0003_actividades_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
    ]
