# Generated by Django 4.0.6 on 2022-08-27 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Club_app', '0007_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fechaPublicacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
