# Generated by Django 4.0.6 on 2022-08-29 18:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club_app', '0008_noticias_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
